# Thanks to:
# https://vadosware.io/post/zero-to-continuous-integrated-testing-a-haskell-project-with-gitlab/
#
#
image: adinapoli/gargantext:v1

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  STACK_OPTS: "--system-ghc"

#before_script:
  #- apt-get update
  #- apt-get install make xz-utils

stages:
  - deps
  - cabal
  - test
  - docs

deps:
  stage: deps
  cache:
    # cache per branch name
    # key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack
      - .stack-root/
      - .stack-work/
      - target
  script:
    - stack -v --nix build --no-terminal --haddock --no-haddock-deps --only-dependencies --fast

docs:
  stage: docs
  cache:
    # cache per branch name
    # key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack
      - .stack-root/
      - .stack-work/
      - target
  script:
    - stack --nix build --no-terminal --haddock --no-haddock-deps --fast
    - cp -R "$(stack path --local-install-root)"/doc ./output
  artifacts:
    paths:
      - ./output
    expire_in: 1 week

test:
  stage: test
  cache:
    # cache per branch name
    # key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack
      - .stack-root/
      - .stack-work/
      - target
  script:
    - stack --nix test --no-terminal --fast

      # TOOO

cabal:
  stage: cabal
  cache:
    # cache per branch name
    # key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .stack
      - .stack-root/
      - .stack-work/
      - .local/
      - .cabal/
      - target
  script:
    - nix-shell && hpack && cabal v2-build --dry-run

