name: gargantext

#         +------------ Layer 3
#         | +--+------- Layer 2
#         | | +-------- Layer 1  : New versions with API changes
#         | | | +-----  Layers * : New versions with API additions
#         | | | | +---  Layers * : New versions without API breaking changes
#         | | | | |
version: '0.0.6.9.8.1'
synopsis: Search, map, share
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-Present: see git logs and README'
license: AGPL-3
homepage: https://gargantext.org
ghc-options: -Wall
dependencies:
  - extra
  - text
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - StrictData
data-files:
  - ekg-assets/index.html
  - ekg-assets/monitor.js
  - ekg-assets/monitor.css
  - ekg-assets/jquery.flot.min.js
  - ekg-assets/jquery-1.6.4.min.js
  - ekg-assets/bootstrap-1.4.0.min.css
  - ekg-assets/chart_line_add.png
  - ekg-assets/cross.png
library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-signatures
  - -Wunused-binds
  - -Wunused-imports
  - -Werror
  - -freduction-depth=300
  exposed-modules:
  - Gargantext
  - Gargantext.API
  - Gargantext.API.Admin.Auth.Types
  - Gargantext.API.Admin.EnvTypes
  - Gargantext.API.Admin.Settings
  - Gargantext.API.Admin.Types
  - Gargantext.API.Dev
  - Gargantext.API.HashedResponse
  - Gargantext.API.Ngrams
  - Gargantext.API.Ngrams.Prelude
  - Gargantext.API.Ngrams.Tools
  - Gargantext.API.Ngrams.Types
  - Gargantext.API.Node
  - Gargantext.API.Node.File
  - Gargantext.API.Node.Share
  - Gargantext.API.Prelude
  - Gargantext.Core
  - Gargantext.Core.NLP
  - Gargantext.Core.Methods.Similarities
  - Gargantext.Core.NodeStory
  - Gargantext.Core.Text
  - Gargantext.Core.Text.Context
  - Gargantext.Core.Text.Corpus.API
  - Gargantext.Core.Text.Corpus.Parsers
  - Gargantext.Core.Text.Corpus.Parsers.CSV
  - Gargantext.Core.Text.Corpus.Parsers.Date.Parsec
  - Gargantext.Core.Text.List.Formats.CSV
  - Gargantext.Core.Text.Metrics
  - Gargantext.Core.Text.Metrics.CharByChar
  - Gargantext.Core.Text.Metrics.Count
  - Gargantext.Core.Text.Metrics.TFICF
  - Gargantext.Core.Text.Prepare
  - Gargantext.Core.Text.Search
  - Gargantext.Core.Text.Terms
  - Gargantext.Core.Text.Terms.Eleve
  - Gargantext.Core.Text.Terms.Mono
  - Gargantext.Core.Text.Terms.Multi.Lang.En
  - Gargantext.Core.Text.Terms.Multi.Lang.Fr
  - Gargantext.Core.Text.Terms.Multi.RAKE
  - Gargantext.Core.Text.Terms.WithList
  - Gargantext.Core.Types
  - Gargantext.Core.Types.Individu
  - Gargantext.Core.Types.Main
  - Gargantext.Core.Utils
  - Gargantext.Core.Utils.Prefix
  - Gargantext.Core.Viz.Graph
  - Gargantext.Core.Viz.Graph.Index
  - Gargantext.Core.Viz.Graph.Tools
  - Gargantext.Core.Viz.Graph.Tools.IGraph
  - Gargantext.Core.Viz.Graph.Types
  - Gargantext.Core.Viz.Phylo
  - Gargantext.Core.Viz.Phylo.API
  - Gargantext.Core.Viz.Phylo.API.Tools
  - Gargantext.Core.Viz.Phylo.PhyloExport
  - Gargantext.Core.Viz.Phylo.PhyloMaker
  - Gargantext.Core.Viz.Phylo.PhyloTools
  - Gargantext.Core.Viz.Phylo.SynchronicClustering
  - Gargantext.Core.Viz.Types
  - Gargantext.Database.Action.Flow
  - Gargantext.Database.Action.Flow.Types
  - Gargantext.Database.Action.User.New
  - Gargantext.Database.Admin.Config
  - Gargantext.Database.Admin.Trigger.Init
  - Gargantext.Database.Admin.Types.Hyperdata
  - Gargantext.Database.Admin.Types.Node
  - Gargantext.Database.Prelude
  - Gargantext.Database.Query.Table.NgramsPostag
  - Gargantext.Database.Query.Table.Node
  - Gargantext.Database.Query.Table.Node.UpdateOpaleye
  - Gargantext.Database.Query.Table.User
  - Gargantext.Database.Schema.Ngrams
  - Gargantext.Defaults
  - Gargantext.Utils.Jobs
  - Gargantext.Utils.Jobs.API
  - Gargantext.Utils.Jobs.Map
  - Gargantext.Utils.Jobs.Monad
  - Gargantext.Utils.Jobs.Queue
  - Gargantext.Utils.Jobs.Settings
  - Gargantext.Utils.Jobs.State
  - Gargantext.Utils.SpacyNLP
  - Gargantext.Utils.Tuple
  dependencies:
  - HSvm
  - KMP
  - MissingH
  - MonadRandom
  - QuickCheck
  - Unique
  - accelerate
  - accelerate-arithmetic
  - accelerate-llvm-native
  - accelerate-utility
  - aeson
  - aeson-lens
  - aeson-pretty
  - array
  - async
  - attoparsec
  - auto-update
  - base >=4.7 && <5
  - base16-bytestring
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - blaze-svg
  - bytestring
  - case-insensitive
  - cassava
  - cereal     # (IGraph)
  - cborg
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - crawlerArxiv
  - crawlerHAL
  - crawlerISTEX
  - crawlerIsidore
  - crawlerPubMed
  - cryptohash
  - data-time-segment
  - deepseq
  - directory
  - duckling
  - ekg-core
  - ekg-json
  - exceptions
  - fast-logger
  - fclabels
  - fgl
  - filelock
  - filepath
  - formatting
  - full-text-search
  - fullstop
  - gargantext-prelude
  - gargantext-graph >= 0.1.0.0
  - graphviz
  - hashable
  - haskell-igraph
  - hlcm
  - hsinfomap
  - hsparql
  - hstatistics
  - http-api-data
  - http-client
  - http-client-tls
  - http-conduit
  - http-media
  - http-types
  - hxt
  - ihaskell
  - ini
  - insert-ordered-containers
  - jose
  - json-stream
  - lens
  - lifted-base
  - listsafe
  - located-base
  - logging-effect
  - matrix
  - monad-control
  - monad-logger
  - morpheus-graphql
  - morpheus-graphql-app
  - morpheus-graphql-core
  - morpheus-graphql-subscriptions
  - mtl
  - natural-transformation
  - network-uri
  - opaleye
  - pandoc
  - parallel
  - parsec
  - patches-class
  - patches-map
  - path
  - path-io
  - postgresql-simple
  - pretty-simple
  - probability
  - process
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - quickcheck-instances
  - rake
  - random
  - rdf4h
  - regex-compat
  - regex-tdfa
  - resource-pool
  - resourcet
  - safe
  - scientific
  - semigroups
  - serialise
  - servant
  - servant-auth
  - servant-auth-client
  - servant-auth-server >= 0.4.4.0
  - servant-auth-swagger
  - servant-blaze
  - servant-cassava
  - servant-client
  - servant-ekg
  - servant-flatten
  - servant-job
  - servant-mock
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-xml
  - simple-reflect
  - singletons # (IGraph)
  - split
  - stemmer
  - stm
  - swagger2
  - taggy-lens
  - tagsoup
  - template-haskell
  - temporary
  - text-conversions
  - text-metrics
  - time
  - time-locale-compat
  - timezone-series
  - transformers
  - transformers-base
  - tuple
  - unordered-containers
  - utf8-string
  - uuid
  - uri-encode
  - validity
  - vector
  - wai
  - wai-app-static
  - wai-cors
  - wai-extra
  - wai-websockets
  - warp
  - wikiparsec
  - websockets
  - wreq
  - xml-conduit
  - xml-types
  - xmlbf
  - yaml
  - zip
  - zlib

executables:
  gargantext-server:
    main: Main.hs
    source-dirs: bin/gargantext-server
    ghc-options:
    - -O2
    - -Wcompat
    - -Wmissing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    - -fprof-auto
    dependencies:
      - base
      - containers
      - gargantext
      - gargantext-prelude
      - vector
      - cassava
      - ini
      - optparse-generic
      - unordered-containers
      - full-text-search

  gargantext-cli:
    main: Main.hs
    source-dirs: bin/gargantext-cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - gargantext
      - gargantext-prelude
      - vector
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers
      - full-text-search

  gargantext-phylo:
    main: Main.hs
    source-dirs: bin/gargantext-phylo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - directory
      - gargantext
      - gargantext-prelude
      - vector
      - parallel
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers
      - cryptohash
      - time 

  gargantext-import:
    main: Main.hs
    source-dirs: bin/gargantext-import
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base
      - servant-server

  gargantext-init:
    main: Main.hs
    source-dirs: bin/gargantext-init
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base

  gargantext-invitations:
    main: Main.hs
    source-dirs: bin/gargantext-invitations
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base


  gargantext-upgrade:
    main: Main.hs
    source-dirs: bin/gargantext-upgrade
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base
      - postgresql-simple

  gargantext-admin:
    main: Main.hs
    source-dirs: bin/gargantext-admin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base


  gargantext-cbor2json:
    main: Main.hs
    source-dirs: bin/gargantext-cbor2json
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - gargantext-prelude
      - base
      - bytestring
      - aeson
      - serialise


tests:
   garg-test:
     main: Main.hs
     source-dirs: src-test
     default-extensions:
     - DataKinds
     - DeriveGeneric
     - FlexibleContexts
     - FlexibleInstances
     - GeneralizedNewtypeDeriving
     - MultiParamTypeClasses
     - NoImplicitPrelude
     - OverloadedStrings
     - RankNTypes
     ghc-options:
     - -threaded
     - -rtsopts
     - -with-rtsopts=-N
     dependencies:
     - base
     - gargantext
     - gargantext-prelude
     - hspec
     - QuickCheck
     - quickcheck-instances
     - time
     - parsec
     - duckling
     - text
     - unordered-containers
   jobqueue-test:
     main: Main.hs
     source-dirs: tests/queue
     ghc-options:
     - -threaded
     - -rtsopts
     - -with-rtsopts=-N
     dependencies:
     - base
     - gargantext
     - hspec
     - async
     - stm
#  garg-doctest:
#    main: Main.hs
#    source-dirs: src-doctest
#    ghc-options:
#    - -O2
#    - -Wcompat
#    - -Wmissing-signatures
#    - -rtsopts
#    - -threaded
#    - -with-rtsopts=-N
#    dependencies:
#    - doctest
#    - Glob
#    - QuickCheck
#    - base
#    - gargantext
#    default-extensions:
#    - DataKinds
#    - DeriveGeneric
#    - FlexibleContexts
#    - FlexibleInstances
#    - GeneralizedNewtypeDeriving
#    - MultiParamTypeClasses
#    - NoImplicitPrelude
#    - OverloadedStrings
#    - RankNTypes
#

