"allow-newer": true
"extra-deps":
- "HSvm-0.1.1.3.22"
- "KMP-0.2.0.0"
- "MissingH-1.4.3.0"
- "Unique-0.4.7.8"
- "dependent-sum-0.7.1.0"
- "fast-tagsoup-1.0.14"
- "fclabels-2.0.5.1"
- "full-text-search-0.2.1.4"
- "fullstop-0.1.4"
- "ghc-parser-0.2.6.0"
- "hgal-2.0.0.2"
- "hsparql-0.3.8"
- "hspec-2.11.1"
- "hspec-core-2.11.1"
- "hspec-discover-2.11.1"
- "hspec-expectations-0.8.3"
- "ihaskell-0.11.0.0"
- "ipython-kernel-0.11.0.0"
- "located-base-0.1.1.1"
- "logging-effect-1.3.12"
- "morpheus-graphql-0.24.3"
- "morpheus-graphql-app-0.24.3"
- "morpheus-graphql-client-0.24.3"
- "morpheus-graphql-code-gen-0.24.3"
- "morpheus-graphql-code-gen-utils-0.24.3"
- "morpheus-graphql-core-0.24.3"
- "morpheus-graphql-server-0.24.3"
- "morpheus-graphql-subscriptions-0.24.3"
- "morpheus-graphql-tests-0.24.3"
- "rake-0.0.1"
- "random-1.2.1"
- "recover-rtti-0.4.3"
- "servant-0.20.1"
- "servant-auth-server-0.4.8.0"
- "servant-auth-swagger-0.2.10.2"
- "servant-client-core-0.20"
- "servant-ekg-0.3.1"
- "servant-flatten-0.2"
- "servant-server-0.20"
- "snap-server-1.1.2.1"
- "stemmer-0.5.2"
- "taggy-0.2.1"
- "taggy-lens-0.1.2"
- "tomland-1.3.3.2"
- "validation-selective-0.2.0.0"
- "vector-0.12.3.0"
- "wai-3.2.4"
- commit: 2b5d69448557e89002c0179ea1aaf59bb757a6e3
  git: "https://github.com/AccelerateHS/accelerate-llvm.git"
  subdirs:
  - "accelerate-llvm-native/"
- commit: 2b5d69448557e89002c0179ea1aaf59bb757a6e3
  git: "https://github.com/AccelerateHS/accelerate-llvm.git"
  subdirs:
  - "accelerate-llvm/"
- commit: 334d05519436bb7f20f9926ec76418f5b8afa359
  git: "https://github.com/AccelerateHS/accelerate.git"
  subdirs:
  - .
- commit: 232db57d6ce0940fcc902adf30a9ed3f3561f21d
  git: "https://github.com/MercuryTechnologies/ekg-json.git"
  subdirs:
  - .
- commit: 91928b5d7f9342e9865dde0d94862792d2b88779
  git: "https://github.com/adinapoli/boolexpr.git"
  subdirs:
  - .
- commit: 23603a832117e5352d5b0fb9bb1110228324b35a
  git: "https://github.com/adinapoli/duckling.git"
  subdirs:
  - .
- commit: e9a29582ac66198dd2c2fdc3f8c8a4b1e6fbe004
  git: "https://github.com/adinapoli/haskell-opaleye.git"
  subdirs:
  - .
- commit: 7533a9ccd3bfe77141745f6b61039a26aaf5c83b
  git: "https://github.com/adinapoli/llvm-hs.git"
  subdirs:
  - "llvm-hs"
- commit: 7533a9ccd3bfe77141745f6b61039a26aaf5c83b
  git: "https://github.com/adinapoli/llvm-hs.git"
  subdirs:
  - "llvm-hs-pure"
- commit: 85533b5d597e6fc5498411b4bcfc76380ec80d71
  git: "https://github.com/adinapoli/text16-compat.git"
  subdirs:
  - .
- commit: b3519a0351ae9515497680571f76200c24dedb53
  git: "https://github.com/adinapoli/wikiparsec.git"
  subdirs:
  - .
- commit: a110807651036ca2228a76507ee35bbf7aedf87a
  git: "https://github.com/alpmestan/accelerate-arithmetic.git"
  subdirs:
  - .
- commit: b9fca8beee0f23c17a6b2001ec834d071709e6e7
  git: "https://github.com/alpmestan/hmatrix.git"
  subdirs:
  - packages/base
- commit: b4182487cfe479777c11ca19f3c0d47840b376f6
  git: "https://github.com/alpmestan/servant-job.git"
  subdirs:
  - .
- commit: bc6ca8058077b0b5702ea4b88bd4189cfcad267a
  git: "https://github.com/alpmestan/sparse-linear.git"
  subdirs:
  - "sparse-linear"
- commit: 8fff32a43df743c8c83428a86dd566a0936a4fba
  git: "https://github.com/chessai/eigen.git"
  subdirs:
  - .
- commit: 10a416b9f6c443866b36479c3441ebb3bcdeb7ef
  git: "https://github.com/delanoe/data-time-segment.git"
  subdirs:
  - .
- commit: 76cae88f367976ff091e661ee69a5c3126b94694
  git: "https://github.com/delanoe/patches-map"
  subdirs:
  - .
- commit: 4fd2edf30c141600ffad6d730cc4c1c08a6dbce4
  git: "https://github.com/robstewart57/rdf4h.git"
  subdirs:
  - .
- commit: a3875fe652d3bb5acb522674c22c6c814c1b4ad0
  git: "https://gitlab.iscpif.fr/amestanogullari/accelerate-utility.git"
  subdirs:
  - .
- commit: eb130c71fa17adaceed6ff66beefbccb13df51ba
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/arxiv-api.git"
  subdirs:
  - .
- commit: 9225d046083853200b9045c8d71161e6a234fc5c
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/epo-proxy-api.git"
  subdirs:
  - .
- commit: bfa9069b4ff70f341ca3244e8aff9e83eb4b8b73
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/hal.git"
  subdirs:
  - .
- commit: e9b594a4718acc06db037f6d3f429a90db76c267
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/isidore.git"
  subdirs:
  - .
- commit: c0a08d62c40a169b7934ceb7cb12c39952160e7a
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/istex.git"
  subdirs:
  - .
- commit: 35a95e7e8da655f868d5420aa29e835a813fa3a2
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/openalex.git"
  subdirs:
  - .
- commit: 300764df4f78ea6175535f9b78b884cc2aa9da61
  git: "https://gitlab.iscpif.fr/gargantext/crawlers/pubmed.git"
  subdirs:
  - .
- commit: 588e104fe7593210956610cab0041fd16584a4ce
  git: "https://gitlab.iscpif.fr/gargantext/gargantext-graph.git"
  subdirs:
  - .
- commit: 618f711a530df56caefbb1577c4bf3d5ff45e214
  git: "https://gitlab.iscpif.fr/gargantext/haskell-gargantext-prelude"
  subdirs:
  - .
- commit: 9f8a2f4a014539826a4eab3215cc70c0813f20cb
  git: "https://gitlab.iscpif.fr/gargantext/haskell-igraph.git"
  subdirs:
  - .
- commit: 1370fea1939e2378ce344e512d80671ac700e787
  git: "https://gitlab.iscpif.fr/gargantext/haskell-infomap.git"
  subdirs:
  - .
- commit: 6f0595d2421005837d59151a8b26eee83ebb67b5
  git: "https://gitlab.iscpif.fr/gargantext/hlcm.git"
  subdirs:
  - .
- commit: eab929d106833ded8011a0d6705135e3fc506a9c
  git: "https://gitlab.iscpif.fr/gargantext/iso639.git"
  subdirs:
  - .
- commit: 3668d28607867a88b2dfc62158139b3cfd629ddb
  git: "https://gitlab.iscpif.fr/gargantext/patches-class.git"
  subdirs:
  - .
- commit: 339fd608341bd2652cf5c0e9e76a3293acffbea6
  git: "https://gitlab.iscpif.fr/gargantext/servant-xml-conduit.git"
  subdirs:
  - .
flags:
  HTTP:
    conduit10: false
    "network-uri": true
    "warn-as-error": false
    "warp-tests": false
  JuicyPixels:
    mmap: false
  MissingH:
    "network--ge-3_0_0": true
  QuickCheck:
    "old-random": false
    templatehaskell: true
  SHA:
    exe: false
  "abstract-deque":
    usecas: false
  accelerate:
    "bounds-checks": true
    debug: false
    "internal-checks": false
    nofib: false
    "unsafe-checks": false
  aeson:
    cffi: false
    "ordered-keymap": true
  "aeson-pretty":
    "lib-only": false
  "ansi-terminal":
    example: false
    "win32-2-13-1": false
  "ansi-wl-pprint":
    example: false
  assoc:
    tagged: true
  async:
    bench: false
  "atomic-primops":
    debug: false
  attoparsec:
    developer: false
  "base-unicode-symbols":
    "base-4-8": true
    "old-base": false
  bifunctors:
    semigroups: true
    tagged: true
  bitvec:
    simd: true
  boring:
    tagged: true
  "bytestring-builder":
    bytestring_has_builder: true
  c2hs:
    base3: true
    regression: false
  cassava:
    "bytestring--lt-0_10_4": false
  "cassava-conduit":
    small_base: true
  cborg:
    "optimize-gmp": true
  cereal:
    "bytestring-builder": false
  "cipher-aes":
    support_aesni: true
  citeproc:
    executable: false
    icu: false
  clock:
    llvm: false
  cmdargs:
    quotation: true
    testprog: false
  comonad:
    containers: true
    distributive: true
    "indexed-traversable": true
  "constraints-extras":
    "build-readme": true
  contravariant:
    semigroups: true
    statevar: true
    tagged: true
  cpphs:
    "old-locale": false
  criterion:
    "embed-data-files": false
    fast: false
  "criterion-measurement":
    fast: false
  cron:
    "lib-werror": false
  "crypto-api":
    all_cpolys: false
  crypton:
    check_alignment: false
    "integer-gmp": true
    old_toolchain_inliner: false
    support_aesni: true
    support_deepseq: true
    support_pclmuldq: true
    support_rdrand: true
    support_sse: false
    use_target_attributes: true
  cryptonite:
    check_alignment: false
    "integer-gmp": true
    old_toolchain_inliner: false
    support_aesni: true
    support_deepseq: true
    support_pclmuldq: false
    support_rdrand: true
    support_sse: false
    use_target_attributes: true
  digest:
    "pkg-config": true
  distributive:
    semigroups: true
    tagged: true
  dlist:
    werror: false
  "double-conversion":
    developer: false
    embedded_double_conversion: true
  entropy:
    donotgetentropy: false
  fgl:
    containers042: true
  "foldable1-classes-compat":
    tagged: true
  formatting:
    "no-double-conversion": true
  "full-text-search":
    "build-search-demo": false
  gargantext:
    "disable-db-obfuscation-executable": false
    "test-crypto": false
  "generic-deriving":
    "base-4-9": true
  "ghc-lib-parser":
    "threaded-rts": true
  "ghc-lib-parser-ex":
    auto: false
    "no-ghc-lib": false
  "ghc-syntax-highlighter":
    dev: false
  graphviz:
    "test-parsing": false
  hashable:
    "integer-gmp": true
    "random-initial-seed": false
  hashtables:
    "bounds-checking": false
    debug: false
    "detailed-profiling": false
    portable: false
    sse42: false
    "unsafe-tricks": true
  hexpat:
    bundle: false
  hlint:
    "ghc-lib": true
    gpl: true
    hsyaml: false
    threaded: true
  hmatrix:
    "disable-default-paths": false
    "no-random_r": false
    openblas: false
  "hmatrix-gsl-stats":
    onlygsl: false
  hsc2hs:
    "in-ghc-tree": false
  hslogger:
    "network--gt-3_0_0": true
  "http-api-data":
    "use-text-show": false
  "http-client":
    "network-uri": true
  "http-conduit":
    aeson: true
  http2:
    devel: false
    h2spec: false
  hxt:
    "network-uri": true
    profile: false
  "hxt-charproperties":
    profile: false
  "hxt-regex-xmlschema":
    profile: false
  ihaskell:
    "use-hlint": true
  "integer-logarithms":
    "check-bounds": false
    "integer-gmp": true
  "io-streams":
    network: true
    nointeractivetests: false
    zlib: true
  "ipython-kernel":
    examples: false
  jose:
    demos: false
  "json-stream":
    conduit: false
  "language-c":
    allwarnings: false
    iecfpextension: true
    usebytestrings: true
  lens:
    "benchmark-uniplate": false
    "dump-splices": false
    inlining: true
    j: false
    "test-hunit": true
    "test-properties": true
    "test-templates": true
    trustworthy: true
  libffi:
    "ghc-bundled-libffi": true
  libyaml:
    "no-unicode": false
    "system-libyaml": false
  "llvm-hs":
    debug: false
    "llvm-with-rtti": false
    "shared-llvm": true
  lzma:
    pkgconfig: true
  "math-functions":
    "system-erf": true
    "system-expm1": true
  megaparsec:
    dev: false
  memory:
    support_bytestring: true
    support_deepseq: true
  "modern-uri":
    dev: false
  "monad-logger":
    template_haskell: true
  "monad-loops":
    base4: true
  "mtl-compat":
    "two-point-one": false
    "two-point-two": false
  network:
    devel: false
  "optics-core":
    "explicit-generic-labels": false
  "optparse-applicative":
    process: true
  "optparse-simple":
    "build-example": false
  pandoc:
    embed_data_files: false
  "parser-combinators":
    dev: false
  parsers:
    attoparsec: true
    binary: true
    parsec: true
  password:
    argon2: true
    bcrypt: true
    pbkdf2: true
    scrypt: true
  path:
    dev: false
  "path-io":
    dev: false
  pointed:
    comonad: true
    containers: true
    "kan-extensions": true
    semigroupoids: true
    semigroups: true
    stm: true
    tagged: true
    transformers: true
    "unordered-containers": true
  "postgresql-libpq":
    "use-pkg-config": false
  "pretty-simple":
    buildexample: false
    buildexe: true
  prettyprinter:
    buildreadme: false
    text: true
  probability:
    splitbase: true
  pureMD5:
    test: false
  "quickcheck-instances":
    "bytestring-builder": false
  reflection:
    slow: false
    "template-haskell": true
  "regex-pcre":
    "pkg-config": true
  "regex-posix":
    "_regex-posix-clib": false
  "regex-tdfa":
    doctest: true
    "force-o2": false
  req:
    dev: false
  retry:
    "lib-werror": false
  scientific:
    "bytestring-builder": false
    "integer-simple": false
  semialign:
    semigroupoids: true
  semigroupoids:
    comonad: true
    containers: true
    contravariant: true
    distributive: true
    tagged: true
    "unordered-containers": true
  semigroups:
    binary: true
    bytestring: true
    "bytestring-builder": false
    containers: true
    deepseq: true
    hashable: true
    tagged: true
    "template-haskell": true
    text: true
    transformers: true
    "unordered-containers": true
  serialise:
    newtime15: true
  shelly:
    "build-examples": false
    lifted: false
  "simple-sendfile":
    "allow-bsd": true
    fallback: false
  skylighting:
    executable: false
  "skylighting-core":
    executable: false
  "snap-core":
    debug: false
    "network-uri": true
    portable: false
  "snap-server":
    "build-pong": false
    "build-testserver": false
    debug: false
    openssl: false
    portable: false
  some:
    "newtype-unsafe": true
  splitmix:
    "optimised-mixer": false
  "streaming-commons":
    "use-bytestring-builder": false
  stringsearch:
    base3: false
    base4: true
  tagged:
    deepseq: true
    transformers: true
  tasty:
    unix: true
  "tasty-bench":
    debug: false
    tasty: true
  texmath:
    executable: false
    server: false
  "text-format":
    developer: false
  "text-metrics":
    dev: false
  "text-short":
    asserts: false
  "text-show":
    "base-4-9": true
    "integer-gmp": true
    "new-functor-classes": true
    "template-haskell-2-11": true
  "text16-compat":
    "enable-golden-test-generation": false
  "time-compat":
    "old-locale": false
  "time-locale-compat":
    "old-locale": false
  tls:
    compat: true
    hans: false
    network: true
  tomland:
    "build-play-tomland": false
    "build-readme": false
  "transformers-base":
    orphaninstances: true
  "transformers-compat":
    five: false
    "five-three": true
    four: false
    "generic-deriving": true
    mtl: true
    three: false
    two: false
  "unicode-collation":
    doctests: false
    executable: false
  "unicode-data":
    ucd2haskell: false
  "unicode-transforms":
    "bench-show": false
    dev: false
    "has-icu": false
    "has-llvm": false
    "use-gauge": false
  "unix-compat":
    "old-time": false
  "unordered-containers":
    debug: false
  "uri-bytestring":
    "lib-werror": false
  "uri-encode":
    "network-uri": true
    tools: false
  vault:
    useghc: true
  vector:
    boundschecks: true
    internalchecks: false
    unsafechecks: false
    wall: false
  "vector-algorithms":
    bench: true
    boundschecks: true
    internalchecks: false
    llvm: false
    properties: true
    unsafechecks: false
  "vector-instances":
    hashable: true
  void:
    safe: false
  "wai-app-static":
    crypton: true
    print: false
  "wai-extra":
    "build-example": false
  "wai-websockets":
    example: true
  warp:
    "allow-sendfilefd": true
    "network-bytestring": false
    "warp-debug": false
    x509: true
  websockets:
    example: false
  wikiparsec:
    "library-only": true
  wreq:
    aws: false
    developer: false
    doctest: true
    httpbin: false
  wuss:
    pedantic: false
  yaml:
    "no-examples": true
    "no-exe": true
  zip:
    dev: false
    "disable-bzip2": false
    "disable-zstd": false
  "zip-archive":
    executable: false
  zlib:
    "bundled-c-zlib": false
    "non-blocking-ffi": false
    "pkg-config": false
  zstd:
    standalone: true
packages:
- .
resolver: "lts-21.17"
"system-ghc": true
